set relativenumber
set nohlsearch
set hidden
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set nowrap
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set termguicolors
set scrolloff=8
set signcolumn=yes
set isfname+=@-@
set clipboard=unnamed,unnamedplus
set showmatch
set cmdheight=1
set updatetime=50
set colorcolumn=120
set cursorline
set autoread
set formatoptions-=cro
set splitright
