vim.scriptencoding = "utf-8"
vim.opt.encoding = "utf-8"
vim.opt.fileencoding = "utf-8"

vim.opt.relativenumber = true
vim.opt.hlsearch = false
vim.opt.hidden = true
vim.opt.errorbells = false
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.nu = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.isfname = "@-@"
vim.opt.clipboard = "unnamed,unnamedplus"
vim.opt.showmatch = true
vim.opt.cmdheight = 1
vim.opt.updatetime = 50
vim.opt.cursorline = true
vim.opt.autoread = true
vim.opt.splitright = true
vim.opt.jumpoptions = "stack"

vim.g.mapleader = " "
